# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_beers_breweries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beers',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
