# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190626_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beers',
            old_name='users',
            new_name='user',
        ),
    ]
