# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190626_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beers',
            name='user',
        ),
        migrations.AddField(
            model_name='beers',
            name='user',
            field=models.ManyToManyField(related_name='beer', to='myapp.users'),
        ),
    ]
