# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-28 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190627_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beers',
            name='abv',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
